name: Update Internship Data

# on:
#   schedule:
#     - cron: 0 0 * * *  # Run every day at midnight
#   workflow_dispatch: # Allow manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: node update-data.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/canada_internships_data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update internship data"
          git push
